  Citizen.CreateThread(function()

    ClearAmbientZoneState("collision_ybmrar", false)
        SetAmbientZoneState("collision_ybmrar", false, false)
           SetScenarioTypeEnabled("WORLD_VEHICLE_POLICE_CAR",false)
             SetScenarioTypeEnabled("WORLD_VEHICLE_POLICE_BIKE",false)
                SetScenarioTypeEnabled("WORLD_VEHICLE_MILITARY_PLANES_SMALL",false)
                   SetScenarioTypeEnabled("WORLD_VEHICLE_MILITARY_PLANES_BIG",false)
                        SetScenarioTypeEnabled("WORLD_VEHICLE_MECHANIC",false)
                            SetScenarioTypeEnabled("WORLD_VEHICLE_EMPTY",false)
                                     SetScenarioTypeEnabled("WORLD_VEHICLE_BUSINESSMEN",false)
                                           SetScenarioTypeEnabled("WORLD_VEHICLE_BIKE_OFF_ROAD_RACE",false)
                                                 StartAudioScene("FBI_HEIST_H5_MUTE_AMBIENCE_SCENE")
                        StartAudioScene("CHARACTER_CHANGE_IN_SKY_SCENE")
                    SetAudioFlag("PoliceScannerDisabled",true)
                SetAudioFlag("DisableFlightMusic",true)
            SetPlayerCanUseCover(PlayerId(),false)
        SetRandomEventFlag(false)
    SetDeepOceanScaler(0.0)
end)